
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
//class to gui for searching emloyee from different things
public class GuiSearchEmployee extends javax.swing.JFrame {

    /**
     * Creates new form SearchEmployeeUI
     */
    public GuiSearchEmployee() {
        Manager.loadDepartments();
        initComponents();
        getContentPane().setBackground(new Color(162, 193, 242));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnName = new javax.swing.JButton();
        btnEpfNum = new javax.swing.JButton();
        btnDesignation = new javax.swing.JButton();
        btnDepartment = new javax.swing.JButton();
        btnAll = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Employee");
        setBackground(new java.awt.Color(102, 102, 255));

        btnName.setBackground(new java.awt.Color(255, 204, 204));
        btnName.setText("Name");
        btnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameActionPerformed(evt);
            }
        });

        btnEpfNum.setBackground(new java.awt.Color(255, 204, 204));
        btnEpfNum.setText("EPF");
        btnEpfNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEpfNumActionPerformed(evt);
            }
        });

        btnDesignation.setBackground(new java.awt.Color(255, 204, 204));
        btnDesignation.setText("Designation");
        btnDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesignationActionPerformed(evt);
            }
        });

        btnDepartment.setBackground(new java.awt.Color(255, 204, 204));
        btnDepartment.setText("Department");
        btnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepartmentActionPerformed(evt);
            }
        });

        btnAll.setBackground(new java.awt.Color(255, 204, 204));
        btnAll.setText("All");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        tfSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Department", "Designation", "Name", "EPF"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("  Employees");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSearch)
                    .addComponent(btnEpfNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDesignation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDepartment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEpfNum)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addGap(8, 8, 8))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAll, btnDepartment, btnDesignation, btnEpfNum, btnName});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        // TODO add your handling code here:
        //showing all the employees
        String[] data=new String[4];
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);//setting rows 0 when starting
        for(Department department:Manager.departmentList){
            for(Designation designation:department.getDesignations()){
                for(Employee employee:designation.getEmployees()){
                    data[0]=department.getDepartmentName();//col 1
                    data[1]=designation.getDesignationName();//col 2
                    data[2]=employee.getName();//col3
                    data[3]=Integer.toString(employee.getEpfNum());//col4
                    tblModel.addRow(data);//adding row to the table
                }
            }
        }
        
    }//GEN-LAST:event_btnAllActionPerformed

    private void btnDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesignationActionPerformed
        // TODO add your handling code here:
        //search employees from the designation
        String designationName=tfSearch.getText();//getting the name of the designation
        String[] data=new String[4];
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);//setting rows 0 when starting
        for(Department department:Manager.departmentList){
            for(Designation designation:department.getDesignations()){
                for(Employee employee:designation.getEmployees()){
                    if(designation.getDesignationName().equals(designationName)){//checking the designation
                        data[0]=department.getDepartmentName();//col1
                        data[1]=designation.getDesignationName();//col2
                        data[2]=employee.getName();//col2
                        data[3]=Integer.toString(employee.getEpfNum());//col3
                        tblModel.addRow(data);//adding the row to the table
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnDesignationActionPerformed

    private void btnEpfNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEpfNumActionPerformed
        // TODO add your handling code here:
        //showing employees have given epf number
        String epf=tfSearch.getText();//getting the epf number
        String[] data=new String[4];
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);//setting rows 0 when starting
        for(Department department:Manager.departmentList){
            for(Designation designation:department.getDesignations()){
                for(Employee employee:designation.getEmployees()){
                    if(employee.getEpfNum()==Integer.valueOf(epf)){//checking the epf number 
                        data[0]=department.getDepartmentName();//col1
                        data[1]=designation.getDesignationName();//col2
                        data[2]=employee.getName();//col3
                        data[3]=Integer.toString(employee.getEpfNum());//col4
                        tblModel.addRow(data);//adding the row for the table
                    }
                }
            }
        }
    }//GEN-LAST:event_btnEpfNumActionPerformed

    private void btnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepartmentActionPerformed
        // TODO add your handling code here:
         //showing employees have given department
        String departmentName=tfSearch.getText();//getting the department name
        String[] data=new String[4];
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);//setting rows 0 when starting
        for(Department department:Manager.departmentList){
            for(Designation designation:department.getDesignations()){
                for(Employee employee:designation.getEmployees()){
                    if(department.getDepartmentName().equals(departmentName)){//checking department
                        data[0]=department.getDepartmentName();//col1
                        data[1]=designation.getDesignationName();//col2
                        data[2]=employee.getName();//col3
                        data[3]=Integer.toString(employee.getEpfNum());//col4
                        tblModel.addRow(data);//adding row to the table
                    }
                }
            }
        }
    }//GEN-LAST:event_btnDepartmentActionPerformed

    private void btnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameActionPerformed
        // TODO add your handling code here:
         //showing employees have given name
        String name=tfSearch.getText();//get input from textfield
        String[] data=new String[4];
        DefaultTableModel tblModel=(DefaultTableModel)jTable1.getModel();
        tblModel.setRowCount(0);//setting rows 0 when starting
        for(Department department:Manager.departmentList){
            for(Designation designation:department.getDesignations()){
                for(Employee employee:designation.getEmployees()){
                    if(employee.getName().equals(name)){//checking the name
                        data[0]=department.getDepartmentName();//col1
                        data[1]=designation.getDesignationName();//col2
                        data[2]=employee.getName();//col3
                        data[3]=Integer.toString(employee.getEpfNum());//col4
                        tblModel.addRow(data);//adding row to the table
                    }
                }
            }
        }
    }//GEN-LAST:event_btnNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiSearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiSearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiSearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiSearchEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiSearchEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private javax.swing.JButton btnDepartment;
    private javax.swing.JButton btnDesignation;
    private javax.swing.JButton btnEpfNum;
    private javax.swing.JButton btnName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
